In [1]:
import numpy as np

In [2]:
#Примеры создания массивов

In [3]:
a = np.array([3, 4, 5, 6]) #создание одномерного массива
a

array([3, 4, 5, 6])

In [4]:
c = np.arange(0, 13, 4) #создание массива от 0 до 12 с шагом 4
c

array([ 0,  4,  8, 12])

In [5]:
b = np.array([[c], [c + 4]]) #создание двумерного массива
b

array([[[ 0,  4,  8, 12]],

       [[ 4,  8, 12, 16]]])

In [6]:
b = np.ones([4, 5]) #создание двумерного массива из единиц
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
b = np.zeros([5, 4]) #создание двумерного массива из нулей
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
b = np.eye(4) #создание единичной матрицы
b 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
b = np.random.uniform(1, 11, (5, 5)) #создание двумерного массива с равномерно распределёнными случайными числами
b

array([[10.29764888,  3.69634592,  7.0393378 ,  4.80862351,  5.50873048],
       [ 8.1836576 ,  4.40554397,  4.25092907,  4.31283879,  4.42238571],
       [ 3.25468928,  7.1613279 , 10.14221195,  2.77672581,  1.60821974],
       [ 3.27817071, 10.35550065,  8.28217501,  7.11774292,  1.85972294],
       [ 5.54869029,  8.28112832, 10.19929377, 10.22892639,  9.14952378]])

In [10]:
#Демонстрация атрибутов

In [11]:
np.set_printoptions(precision=2) #отбрасывание дробной части до стоых при выводе
print(f'Массив: \n {b}')
print(f'Размеры массива: {b.shape}')
print(f'Тип данных: {b.dtype}')

Массив: 
 [[10.3   3.7   7.04  4.81  5.51]
 [ 8.18  4.41  4.25  4.31  4.42]
 [ 3.25  7.16 10.14  2.78  1.61]
 [ 3.28 10.36  8.28  7.12  1.86]
 [ 5.55  8.28 10.2  10.23  9.15]]
Размеры массива: (5, 5)
Тип данных: float64


In [12]:
#Примеры индексирования и срезов

In [13]:
b[2][2] #элемент в центре матрицы

np.float64(10.142211953484866)

In [14]:
b[:3] #первые три строки

array([[10.3 ,  3.7 ,  7.04,  4.81,  5.51],
       [ 8.18,  4.41,  4.25,  4.31,  4.42],
       [ 3.25,  7.16, 10.14,  2.78,  1.61]])

In [15]:
b[::,1:4] #три столбца в середине массива

array([[ 3.7 ,  7.04,  4.81],
       [ 4.41,  4.25,  4.31],
       [ 7.16, 10.14,  2.78],
       [10.36,  8.28,  7.12],
       [ 8.28, 10.2 , 10.23]])

In [16]:
#Примеры векторных операций и базовых статистик

In [17]:
a * 2 #поэлементное умножение массива

array([ 6,  8, 10, 12])

In [18]:
a - 2 #поэлементное вычитание массива

array([1, 2, 3, 4])

In [19]:
a + c #поэлементное сложение двух массивов

array([ 3,  8, 13, 18])

In [20]:
print(f'Минимальное: {np.min(a + c)}')
print(f'Максимальное: {np.max(a + c)}')
print(f'Среднее: {np.mean(a + c)}')

Минимальное: 3
Максимальное: 18
Среднее: 10.5
